name: "Publish"

on: 
  push: 
  branches:
    - master

jobs:
  release:
    name: To the moon!
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
      - name: Publish
        run: npm publish --access public
        env: 
          NODE_AUTH_TOKEN: ${{secrets.NODE_AUTH_TOKEN}}

